# ビルドステージ
FROM golang:1.22.2 as build

# 作業ディレクトリを設定
WORKDIR /backend/api  # ここはプロジェクトのルートディレクトリに合わせて変更

# 依存関係ファイルを追加
COPY go.mod ./
COPY go.sum ./

# 依存関係をダウンロード
RUN go mod download

# アプリケーションソースコードを追加
COPY . ./ 

# アプリケーションをビルド
RUN go build -o main ./main.go

EXPOSE 8080

# アプリケーションを実行
CMD ["backend/api/main"]
