# ビルドステージ
FROM golang:1.22.2 as build

# 作業ディレクトリを設定
WORKDIR /api

# 依存関係ファイルを追加
COPY go.mod ./
COPY go.sum ./

# 依存関係をダウンロード
RUN go mod download

# アプリケーションソースコードを追加
ADD main.go ./

# アプリケーションをビルド
RUN go build -o main ./main.go

# 実行ステージ
FROM debian:stable-slim as app

WORKDIR /api

# ビルド成果物をコピー
COPY --from=build /api/main .

# 必要なポートを公開
EXPOSE 8080

# アプリケーションを実行
CMD ["/api/main"]