// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hashtag.sql

package sqlc

import (
	"context"
)

const createHashtag = `-- name: CreateHashtag :exec
INSERT INTO hashtags (
	hashtag, tweetId
) VALUES (
	?, ?
)
`

type CreateHashtagParams struct {
	Hashtag string `json:"hashtag"`
	Tweetid int32  `json:"tweetid"`
}

func (q *Queries) CreateHashtag(ctx context.Context, arg CreateHashtagParams) error {
	_, err := q.db.ExecContext(ctx, createHashtag, arg.Hashtag, arg.Tweetid)
	return err
}

const deleteHashtag = `-- name: DeleteHashtag :exec
DELETE FROM hashtags
WHERE tweetId = ?
`

func (q *Queries) DeleteHashtag(ctx context.Context, tweetid int32) error {
	_, err := q.db.ExecContext(ctx, deleteHashtag, tweetid)
	return err
}

const updateHashtag = `-- name: UpdateHashtag :exec
UPDATE hashtags
SET hashtag = ?
WHERE tweetId = ?
`

type UpdateHashtagParams struct {
	Hashtag string `json:"hashtag"`
	Tweetid int32  `json:"tweetid"`
}

func (q *Queries) UpdateHashtag(ctx context.Context, arg UpdateHashtagParams) error {
	_, err := q.db.ExecContext(ctx, updateHashtag, arg.Hashtag, arg.Tweetid)
	return err
}
