// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: impression.sql

package sqlc

import (
	"context"
)

const getImpression = `-- name: GetImpression :one
SELECT impressions
FROM tweets
WHERE tweetId = ?
`

func (q *Queries) GetImpression(ctx context.Context, tweetid int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getImpression, tweetid)
	var impressions int32
	err := row.Scan(&impressions)
	return impressions, err
}

const plusImpression = `-- name: PlusImpression :exec
UPDATE tweets
SET impressions = impressions + 1
WHERE tweetId = ?
`

func (q *Queries) PlusImpression(ctx context.Context, tweetid int32) error {
	_, err := q.db.ExecContext(ctx, plusImpression, tweetid)
	return err
}
