// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: listing.sql

package sqlc

import (
	"context"
)

const getListing = `-- name: GetListing :many
SELECT listingid, userid, tweetid, created_at, listingname, listingdescription, listingprice, stock from listing
WHERE listingId = ?
`

func (q *Queries) GetListing(ctx context.Context, listingid int32) ([]Listing, error) {
	rows, err := q.db.QueryContext(ctx, getListing, listingid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.Listingid,
			&i.Userid,
			&i.Tweetid,
			&i.CreatedAt,
			&i.Listingname,
			&i.Listingdescription,
			&i.Listingprice,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListingByTweet = `-- name: GetListingByTweet :one
SELECT listingid, userid, tweetid, created_at, listingname, listingdescription, listingprice, stock from listing
WHERE tweetId = ?
`

func (q *Queries) GetListingByTweet(ctx context.Context, tweetid int32) (Listing, error) {
	row := q.db.QueryRowContext(ctx, getListingByTweet, tweetid)
	var i Listing
	err := row.Scan(
		&i.Listingid,
		&i.Userid,
		&i.Tweetid,
		&i.CreatedAt,
		&i.Listingname,
		&i.Listingdescription,
		&i.Listingprice,
		&i.Stock,
	)
	return i, err
}

const getUserListings = `-- name: GetUserListings :many
SELECT listingid, userid, tweetid, created_at, listingname, listingdescription, listingprice, stock from listing
WHERE userId = ?
`

func (q *Queries) GetUserListings(ctx context.Context, userid string) ([]Listing, error) {
	rows, err := q.db.QueryContext(ctx, getUserListings, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.Listingid,
			&i.Userid,
			&i.Tweetid,
			&i.CreatedAt,
			&i.Listingname,
			&i.Listingdescription,
			&i.Listingprice,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
